//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class WheelSpinMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/WheelSpin";
        public override string RosMessageName => k_RosMessageName;

        public float left;
        public float right;

        public WheelSpinMsg()
        {
            this.left = 0.0f;
            this.right = 0.0f;
        }

        public WheelSpinMsg(float left, float right)
        {
            this.left = left;
            this.right = right;
        }

        public static WheelSpinMsg Deserialize(MessageDeserializer deserializer) => new WheelSpinMsg(deserializer);

        private WheelSpinMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.left);
            deserializer.Read(out this.right);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.left);
            serializer.Write(this.right);
        }

        public override string ToString()
        {
            return "WheelSpinMsg: " +
            "\nleft: " + left.ToString() +
            "\nright: " + right.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
