//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class TwistServiceResponse : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/TwistService";
        public override string RosMessageName => k_RosMessageName;

        public TwistMsg output;

        public TwistServiceResponse()
        {
            this.output = new TwistMsg();
        }

        public TwistServiceResponse(TwistMsg output)
        {
            this.output = output;
        }

        public static TwistServiceResponse Deserialize(MessageDeserializer deserializer) => new TwistServiceResponse(deserializer);

        private TwistServiceResponse(MessageDeserializer deserializer)
        {
            this.output = TwistMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.output);
        }

        public override string ToString()
        {
            return "TwistServiceResponse: " +
            "\noutput: " + output.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
