//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class TwistServiceRequest : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/TwistService";
        public override string RosMessageName => k_RosMessageName;

        public TwistMsg input;

        public TwistServiceRequest()
        {
            this.input = new TwistMsg();
        }

        public TwistServiceRequest(TwistMsg input)
        {
            this.input = input;
        }

        public static TwistServiceRequest Deserialize(MessageDeserializer deserializer) => new TwistServiceRequest(deserializer);

        private TwistServiceRequest(MessageDeserializer deserializer)
        {
            this.input = TwistMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.input);
        }

        public override string ToString()
        {
            return "TwistServiceRequest: " +
            "\ninput: " + input.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
