//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class Vector3ServiceRequest : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/Vector3Service";
        public override string RosMessageName => k_RosMessageName;

        public Vector3Msg input;

        public Vector3ServiceRequest()
        {
            this.input = new Vector3Msg();
        }

        public Vector3ServiceRequest(Vector3Msg input)
        {
            this.input = input;
        }

        public static Vector3ServiceRequest Deserialize(MessageDeserializer deserializer) => new Vector3ServiceRequest(deserializer);

        private Vector3ServiceRequest(MessageDeserializer deserializer)
        {
            this.input = Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.input);
        }

        public override string ToString()
        {
            return "Vector3ServiceRequest: " +
            "\ninput: " + input.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
