//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class Vector3ServiceResponse : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/Vector3Service";
        public override string RosMessageName => k_RosMessageName;

        public Vector3Msg output;

        public Vector3ServiceResponse()
        {
            this.output = new Vector3Msg();
        }

        public Vector3ServiceResponse(Vector3Msg output)
        {
            this.output = output;
        }

        public static Vector3ServiceResponse Deserialize(MessageDeserializer deserializer) => new Vector3ServiceResponse(deserializer);

        private Vector3ServiceResponse(MessageDeserializer deserializer)
        {
            this.output = Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.output);
        }

        public override string ToString()
        {
            return "Vector3ServiceResponse: " +
            "\noutput: " + output.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
